### ISSUE TITLE
Exclude rulesets triggering MCB

### ISSUE THREAD

**Issue by Bisaloo** [tenta-browser/go-https-everywhere#1]
HTTPS Everywhere has some rulesets triggering mixed content blocking. Such rulesets (such as [this one](https://github.com/EFForg/https-everywhere/blob/203375992d37e878d585e49d050fea283f51e390/src/chrome/content/rules/NYDailyNews.com-falsemixed.xml)) are marked with `platform="mixedcontent"`.

It may cause complete breakage of some websites. For example, try visiting nydailynews.com on Tenta Browser. You will get automatically redirected to https://www.nydailynews.com/ which is pretty much unusable.

You should probably discard `platform="mixedcontent"` rulesets, as you are doing with `default_off` rulesets.

**Comment by shadrick** [comment]
Hi!
Thank you for your feedback!
We will investigate and apply a fix asap.

**Comment by shadrick** [comment]
Closing this, commit 1747ea4d30ce309c8d869854b60d2ccee308d354 fixes the issue.

**Comment by Bisaloo** [comment]
Also, I don't know which certificates are shipped with the browser but about ~20 rulesets have `platform="cacert"` to secure targets serving a [CAcert certificate](https://www.cacert.org/). Maybe you will need to remove those as well.

`platform="mixedcontent"` and `platform="cacert"` are the only two platforms currently in use.

**Comment by shadrick** [comment]
Thanks!
I was under the impression that mixedcontent is the only platform.

**Comment by shadrick** [comment]
Disabled cacert platform too. (commit 8211474a484b2aac01810ffa14daa60c10b002b4)
Closing the issue.
Thanks again for your feedback, @Bisaloo !
